# Generated by Django 5.0 on 2024-01-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0001_initial'),
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('HSN', models.CharField(max_length=255)),
                ('stock_in_hand', models.IntegerField()),
                ('godown_name', models.CharField(max_length=255)),
                ('godown_address', models.CharField(max_length=255)),
                ('stock_keeping', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.items')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
