# Generated by Django 5.0 on 2024-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
