# Generated by Django 5.0 on 2024-02-05 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='godown',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Company_Staff.godown'),
            preserve_default=False,
        ),
    ]
