# Generated by Django 5.0 on 2024-01-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_alter_holiday_end_date_alter_holiday_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='company',
        ),
    ]
