# Generated by Django 5.0 on 2024-02-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_godownhistory'),
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='godownhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godownhitory', to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='godownhistory',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godownhitory', to='Company_Staff.godown'),
        ),
        migrations.AlterField(
            model_name='godownhistory',
            name='login_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godownhitory', to='Register_Login.logindetails'),
        ),
    ]
