# Generated by Django 5.0 on 2024-01-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_remove_holiday_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='godown',
            name='company',
        ),
    ]
