# Generated by Django 5.0 on 2024-01-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_remove_godown_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='godown',
            name='active_log',
            field=models.ForeignKey(default='active', on_delete=django.db.models.deletion.CASCADE, related_name='godown_active_logs', to='Company_Staff.items'),
        ),
    ]
