# Generated by Django 5.0 on 2024-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_godown_active_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='activation_tag',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
