# Generated by Django 5.0 on 2024-01-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_alter_items_activation_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godown',
            name='active_log',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='godown_active_logs', to='Company_Staff.items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='activation_tag',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
