# Generated by Django 5.0 on 2024-02-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0010_remove_commentholiday_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentholiday',
            name='holiday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.holiday'),
            preserve_default=False,
        ),
    ]
