# Generated by Django 5.0 on 2024-02-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0012_holiday_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
