# Generated by Django 5.0 on 2024-02-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_holiday_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentholiday',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='commentholiday',
            name='holiday',
        ),
    ]
