# Generated by Django 5.0 on 2024-01-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_rename_active_log_godown_activation_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='activation_tag',
            field=models.CharField(max_length=255),
        ),
    ]
