# Generated by Django 5.0 on 2024-02-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_remove_commentholiday_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentholiday',
            name='holidaymonth',
            field=models.DateField(),
        ),
    ]
