# Generated by Django 5.0 on 2024-02-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_alter_commentholiday_holidaymonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentholiday',
            name='holidaymonth',
            field=models.CharField(max_length=7),
        ),
    ]
