# Generated by Django 5.0 on 2024-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_rename_activation_log_godown_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
