# Generated by Django 5.0 on 2024-01-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_rename_is_active_godown_is_active1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='godown',
            name='is_active1',
        ),
    ]
