# Generated by Django 5.0 on 2024-01-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0018_remove_godown_is_active1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='is_active',
        ),
    ]
